name: "Test"
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Pipeline:
    runs-on: ubuntu-latest
    container: docker

    steps:
    - uses: actions/checkout@v2

    - name: Build Image
      run: docker build -t biar --target dependencies .

    - name: Checks
      run: docker run biar make checks

    - name: Tests
      run: docker run biar make tests
